voxpupuli/puppet-blacksmith

README.md, features/update_version.feature, lib/puppet_blacksmith/modulefile.rb, lib/puppet_blacksmith/rake_tasks.rb, lib/puppet_blacksmith/version_helper.rb, spec/puppet_blacksmith/modulefile_spec.rb
This may be controversial, but I'd love a discussion. I think this functionality is valuable, but contrary to what I'd like to believe, I don't speak for everybody.
This retains the original behavior of bumping the patch version with module:bump (even though the docs said it bumped the minor version). I think this would technically be a breaking change as it enforces Semantic Versioning wheras we were using Gem::Version previously, which isn't SemVer.
Because of the way Puppet has decided to vendor the 'Semantic' gem we're unable to use that namespace because it conflicts with the vendored implementation. This PR vendors our own implementation of the 'Semantic' gem in the Blacksmith::VersionHelper namespace. Not sure if this is the best way to do it, but I can't think of a better way. …
=> Enable bumping semantic version elements.

README.md, features/update_version.feature, lib/puppet_blacksmith/modulefile.rb, lib/puppet_blacksmith/rake_tasks.rb, lib/puppet_blacksmith/version_helper.rb
Allows setting the exact version using the BLACKSMITH_FULL_VERSION env var in combination with the bump:full rake task. Useful for example when CI tool manages the version label for the puppet module
=> Added bump:full rake task

README.md, lib/puppet_blacksmith/forge.rb, spec/puppet_blacksmith/forge_spec.rb
Prior to this a user could set the credential information (username,
password, and url of the forge) via a file located at
~/.puppetforge.yml.
This commit allows users to set the environment variables
- BLACKSMITH_FORGE_URL
- BLACKSMITH_FORGE_USERNAME
- BLACKSMITH_FORGE_PASSWORD
to set the url, username, and password values respectively.
This eases publishing under multiple usernames on the forge as well as
pushing to multiple forges by users (and CI systems) by allowing a
method of setting variables that is not per user wide (an issue with a
credentials file in the user's home directory).
Environment variables will take precedence over values set in a
credentials file.
=> Allow setting credentials info via env vars

lib/puppet_blacksmith/forge.rb, spec/puppet_blacksmith/forge_spec.rb
We now search the .puppetforge.yml in current working dir first.
Fallback to home dir if not found.
=> Allow loading forge credentials from project dir

README.md, lib/puppet_blacksmith/rake_tasks.rb
Add 'version', 'version:next' and 'version:next:[patch|major|minor]' commands to output the current or next version of module.
Useful for wrapping Blacksmith with git flow for example.
The naming structure was the most sensible I could think of, however could equally use 'module:next_version', 'module:version_next' etc...
=> Add version related commands for displaying current or next versions.

README.md
- Remove the link to https://maestro.maestrodev.com/projects/67/compositions/326, it doesn't seem to be active.
- Update the Travis URL to point to voxpupuli's namespace
=> update build status badge source

.travis.yml
Extended maintenance of ruby 1.9.3 ended 2 years ago. And its blocking my other PR. AND puppet no longer supports it.
=> (maint) remove ruby 1.9 from travis

lib/puppet_blacksmith/rake_tasks.rb
When starting to use blacksmith to manage versioning of my puppet modules i ran into issue #38. This PR fixes the order of the release workflow.
=> fix rake module release order

README.md, lib/puppet_blacksmith/modulefile.rb, lib/puppet_blacksmith/rake_tasks.rb, spec/puppet_blacksmith/modulefile_spec.rb
We would like the ability to change the modules version to any version. This new rake task goes around bump levels and accepts any version as a parameter.
=> (MODULES-4344) bump_to_version rake task

.travis.yml, Changelog.md, lib/puppet_blacksmith/version.rb
Something went wrong with the 4.1.1 release that resulted in an incorrect checksum on rubygems. Possible that's because we have multiple jobs attempting to release so it could have been some concurrency issue. This updates the Travis config to only deploy once.
Closes GH-60
=> Release 4.1.2

lib/puppet_blacksmith/version_helper.rb, spec/data/metadata.json, spec/puppet_blacksmith/modulefile_spec.rb
Previously 1.2.3-rc0 bump would be increased to 1.2.4.
Also cleans up some testing code.
=> Handle RC versions while patching

README.md, lib/puppet_blacksmith/rake_tasks.rb
Update description for `module:release` task to follow change in https://github.com/voxpupuli/puppet-blacksmith/pull/42 .
=> Update description for module:release task

lib/puppet_blacksmith/forge.rb
The `upload` method in the `forge.rb` class was refactored, but one
error message that relied on variables which used to be defined in the
method was not updated with the new variables that are in scope for the
method. This removes the variables that now refer to nothing (and thus
throw and error when they're referenced), and replaces them with
variables that are in scope for the `upload` function.
Closes GH-74
=> (maint) Remove outdated variable reference

spec/data/Modulefile
914f35d2054591f50708912c9500351b775fe3a3 removed Modulefile support, but left in this fixture that's now unused.
=> Remove Modulefile fixture

README.md, lib/puppet_blacksmith/forge.rb
Pushing a module to a JFrog Artifactory can be authenticated by its API key. This PR enables the use of this mechanism.
... and I put some documentation about artifactory type module deployment.
=> Enable Artifactory access via API key

README.md, features/git.feature, features/module.feature, features/push.feature, features/update_dependency.feature, features/update_version.feature, lib/puppet_blacksmith/rake_tasks.rb, puppet-blacksmith.gemspec
This decouples building modules from Puppet <= 5 / PDK.
Currently untested so a draft.
=> Use puppet-modulebuilder to build modules

cucumber.yml
This avoids a deprecation warning.
=> Use the modern cucumber syntax

Gemfile
Since 5.0.0 the minimum Ruby version is 2.4 so this condition is never true.
=> Drop old gem dependency

lib/puppet_blacksmith/modulefile.rb, lib/puppet_blacksmith/rake_tasks.rb, spec/data/metadata-different-author.json, spec/data/metadata-no-author.json, spec/puppet_blacksmith/modulefile_spec.rb
There is an author field in metadata.json, but `pdk build` always uses
the module's namespace when building the tarball. Therefore, Blacksmith
should do the same and not even use the author field.
=> Forge upload should always use namespace

lib/puppet_blacksmith/rake_tasks.rb, puppet-blacksmith.gemspec
Version 0.2 has a slightly simpler API but more importantly, it always ignores .git which means a release doesn't accidentally upload the full git repo. Previously 0.2 was allowed, but this enforces it.
=> Use puppet-modulebuilder ~> 0.2

lib/puppet_blacksmith/rake_tasks.rb
The task is available in puppetlabs_spec_helper with the same code.
Previously puppet-blacksmith used the task from PSH but didn't require
it and didn't depend on it in the gemspec. Instead of adding the
dependencies we implement it here.
=> Implement `clean` rake task

.github/workflows/test.yml
This is required for the actions to pass. We previously did this in travis as well.
=> GHA: Set git user/email

puppet-blacksmith.gemspec
All tests pass fine without it. @ekohl I didn't dig further down, maybe you remember why you moved puppet from a dependency to a dev dependency in #45. But I think it's safe to drop it now for real.
=> remove unused puppet testing dependency
